# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseCocialLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'FacebookSDK'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKLoginKit'
	pod 'Firebase/Core'
  pod 'Firebase/FIRAuth'

  # Pods for FirebaseCocialLogin

  target 'FirebaseCocialLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseCocialLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
